services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: geno
      MONGO_INITDB_ROOT_PASSWORD: secret-mongo

  app:
    # Build image nodeserver from Dockerfile in GitHub repo
    image: nodejs-cicd
    build: https://github.com/CleverseAcademy/nodejs-cicd.git#develop
    environment:
      MONGODB_USERNAME: geno
      MONGODB_PASSWORD: secret-mongo
      MONGODB_HOST: mongodb
    ports:
      - "8000:8000"
